import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-faqs',
  templateUrl: './faqs.component.html',
  styleUrls: ['./faqs.component.css']
})
export class FaqsComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

  panels = [
    { title: 'What is Data Roaming?', content: 'Data roaming occurs when you use data connection outside of your carriers coverage zone. Your mobile network can make substantial charges for roaming outside of your network coverage zone and you may end up with an enormous bill without realising it.', isOpen: false },
    { title: 'What products does Roambuddy offer for roaming?', content: 'Roambuddy offers data roaming plans with a coverage of over 180 countries and these plans are useable on any eSIM compatible phones. The eSIM compatible list is on the home page.    ', isOpen: false },
    { title: 'What is a data SIM Card?', content: 'A data only SIM a data allowance that allows users to have mobile Internet on their device, but no minutes for calling or texts for SMS. However, users can still make calls or send messages through applications like Skype, Whatsapp, Facebook Messenger etc ', isOpen: false },
    { title: 'What is a data roaming eSIM?', content: 'A data only eSIM is a product that you can install digitally and allow you to connect to the mobile internet wherever you purchased the data plan for. The data plan is only for mobile internet and does not come with Voice or SMS services. However, users can still make calls or send messages through applications like Skype, WhatsApp, Facebook Messenger, Viber, WeChat, etc.', isOpen: false },
    { title: 'What is the difference between a mobile SIM and a data SIM Card?', content: 'A mobile SIM allows users to make standard phone calls, send SMS, and connect to the internet via mobile data, while a data SIM card provides only mobile data. While you cannot make standard voice calls and SMS from a phone number using a data only SIM card, internet-based messaging (like WhatsApp and Facebook Messenger) and internet calling (Skype and Viber) are practical alternatives. Roambuddy\'s Data eSIM comes with a data plan for various destinations around the world. It is a prepaid mobile service that allows you to access the Internet and stay connected wherever you are in the world and without paying expensive roaming fees to your local operator when roaming abroad.', isOpen: false },
    { title: 'How does a roaming SIM work?', content: 'Mobile operators enter into roaming agreements with other networks; so, if your SIM card\'s home network is not available, it can connect to a different mobile network operator. This roaming feature is especially useful when you are traveling abroad and need to connect to the internet via mobile data. However, roaming fees are very often costly. A more practical and convenient way to stay connected to the internet while travelling is to purchase an international eSIM with a data roaming plan. The Roambuddy service provides eSIM with data plans which are for various destinations around the world and at affordable rates. It is a prepaid mobile service that allows you to access the Internet and stay connected wherever you are in the world and without paying expensive roaming fees.', isOpen: false },
    { title: 'What is a data plan?', content: 'A data plan is a service offered by mobile operators and carriers that allows users to access the internet via 3G, 4G, LTE, or 5G networks. Data plans can come in a variety of costs and sizes depending on the mobile carrier. How much data you need ultimately depends on your internet activities and daily usage. Roambuddy\'s Data eSIM provides data plans for various destinations around the world. It is a prepaid mobile service that allows you to access the Internet and stay connected wherever you are in the world and without paying expensive roaming fees.', isOpen: false },
    { title: 'What is a data enabled SIM card?', content: 'A data enabled SIM card provides mobile data internet connection on a SIM card compatible device such as smartphones, tablets, and pocket Wi-Fi devices. Using a data SIM card is a good option to connect to the internet when Wi-Fi is not available. The Roambuddy Data eSIM provides data plans for eSIM compatible phones or devices. It is a prepaid mobile service that allows you to access the Internet and stay connected wherever you are in the world and without paying expensive roaming fees.', isOpen: false },
    { title: 'What is an MVNO or Mobile Virtual Network Operator?', content: 'An MVNO (or Mobile Virtual Network Operator) is an entity that enters into a business agreement with Mobile Network Operators to obtain airtime in bulk, including voice calls, SMS, and mobile data. The airtime is acquired at wholesale rate and the MVNO resells the airtime at their own retail rates. MVNOs do not own the infrastructure to provide the services. However, an MVNO may maintain their own customer service, billing systems, marketing, and sales staff. Roambuddy is not a MVNO but essentially a marketplace that has agreements with global aggregators that allow us to package the best-priced roaming plans for eSIM compatible phones or Mobile Wi-Fi devices.', isOpen: false },
    { title: 'What is a Travel SIM Card?', content: 'A travel SIM card allows you to connect to a local network in various countries around the world. In this manner, you can avoid excessive roaming fees that your local operator or carrier may charge when you are abroad. While buying a local SIM card may prove marginally cheaper if you are staying in one country for extended periods of time, a travel SIM is a far more flexible option for frequent travelers, especially if you have several destinations during your trip. Travel SIM cards are all about convenience. Here are some advantages of using a travel SIM card like the Roambuddy Data SIM: Having one SIM for multi-country trips is so much less hassle. You can manage spend in an online account and top up without any language barriers. You get low rates for data worldwide. You get more coverage than the average SIM as international SIM cards are designed specifically for traveling. The Roambuddy Data SIM is a data only travel SIM card. A data only SIM has a data allowance that allows users to have mobile Internet on their device, but no minutes for calling or texts for SMS. However, users can still make calls or send messages through applications like Skype, Whatsapp, Facebook Messenger, Viber, WeChat, etc.', isOpen: false },
    { title: 'What is eSIM?', content: 'An eSIM profile contains carrier and network subscription information, just like a normal SIM card. However, instead of coming in the form of a physical chip, it is downloaded directly into your phone. eSIM is only usable on devices that support eSIM technology.', isOpen: false },
    { title: 'Is my Smartphone eSIM enabled?', content: 'Below are some popular devices that support the eSIM functionality: iPhones models: XR, XS, XS Max, 11 series, 12 series, SE 2020 iPads: 10.2, Air, Mini 2019, Pro 11, Pro 12.9 Google Pixel 3/3a, 4 and all the later models Samsung Galaxy S20 series; Note 20 series; Fold, Z Flip Motorola Razr smartphone Huawei P40 and P40 Pro Microsoft Surface Duo If in doubt, always check your device specifications to ensure whether it supports eSIM or not. IMPORTANT NOTE Certain iPhone models are produced for the Chinese market have 2 physical SIM card slots and do not support eSIM. If your iPhone can take 2 physical SIM cards you won\'t be able to use eSIM. Samsung: Samsung restricts eSIM capability by software in some markets. To check, go to Settings - Connections - SIM Card Manager. If you can see the \'Add Mobile Plan\' tab in the eSIMs section, you can use eSIM. Finally, if your device is locked to a specific carrier due to a contract, it needs to be unlocked first in order to use eSIMs sold on our platform.', isOpen: false },
    { title: 'Can I use eSIM with my smartwatch?', content: 'Yes. eSIMs can be used on smartwatches and other wearables that support independent mobile connectivity via eSIM. Please refer to your smartwatch manufacturer guide to confirm the eSIM capability and activation instructions for your smartwatch. IMPORTANT NOTE: Apple Watch is NOT SUPPORTED. Apple watch requires sharing of the same subscription with your iPhone. Please contact your carrier to check if they can help you with connecting your Apple watch to the mobile network.', isOpen: false },
    { title: 'Do I get a phone number with your eSIM?', content: 'No, all our plans provide Mobile Data only and do not come with a phone number nor the option to send or receive SMS.', isOpen: false },
    { title: 'How do I install and activate the eSIM?', content: 'When you place the order and before we share the QR code to scan to install on your phone, we will share video instructions as well as step by step instructions on how to install and activate the eSIM.', isOpen: false },
    { title: 'Which mobile network will the eSIM connect to?', content: 'Our providers have agreements with various mobile network operators across the globe. In eligible countries, your eSIM will automatically connect to a major local network in eligible countries based on the bundle you purchased.', isOpen: false },
    { title: 'Can I use the same eSIM across multiple countries or regions and on different trips?', content: 'Sure! The country coverage list is displayed in the product detail section. You can freely move between different countries shown in the coverage list and you will remain connected. You can also use your eSIM on multiple trips as long as it has remaining data allowance and validity days. Today we offer country, regional as well as Global plans ranging from 7 - 30 days.', isOpen: false },
    { title: 'Can I install multiple eSIMs on my phone?', content: 'Yes, you can. You can store several eSIM profiles in your phone, but you need to choose only one that will be active along with your primary physical SIM. So, the dual SIM functionality means having Your primary physical SIM. One of your stored eSIM profiles active at the same time.', isOpen: false },
    { title: 'Can I delete eSIMs on my phone?', content: 'Only delete eSIMs from your phone settings if you have fully consumed your data package, or the validity has expired. Once deleted, an eSIM cannot be restored and you will need to buy a new one.', isOpen: false },
    { title: 'What are the benefits of eSIM?', content: 'Use two connections on the same phone: eSIM finally brings the dual SIM convenience to iPhone! By having two connections simultaneously active, you can Receive calls and SMSes on both. Choose which one you would like to use for phone calls. Choose which one you would like to use for SMS. Choose which one you would like to use for mobile data. Easily switch providers: You can easily switch between networks when you’re abroad. Simply purchase your eSIM data package from Roambuddy or another provider, add it to your device and you’re connected! Eco-Friendly: Reduce the waste of manufacturing, shipping, packaging and disposing of plastic SIM cards.', isOpen: false },
    { title: 'How can I check the balance or how much data do I have left?', content: 'The easiest way to check the balance or how much data you have left is to go to Settings, Cellular Data, Data Usage. Here, you should be able to see all the data usage for the selected period.', isOpen: false },
    { title: 'What if I run out of data before the expiry date?', content: 'You can always purchase another eSIM for the same destination or region. However, note that your balance will not carry over from one eSIM to another.', isOpen: false },
    { title: 'Can I share data with other devices by enabling tethering?', content: 'Yes, you can. Most eSIMs can be used as a mobile hotspot and connect other devices to the internet via tethering. You may want to check with your provider to confirm the ability to use their eSIM for hotspot and tethering.', isOpen: false },
    { title: 'Does my eSIM expire?', content: 'Yes, your eSIM will expire. Each plan comes with validity ranging from 7 - 30 days. If you do not use all your data within the validity period, it will be lost. Once the validity expires, the eSIM profile can be deleted.', isOpen: false },
    { title: 'Can I buy a new plan without buying a new eSIM?', content: 'If your current eSIM plan is still valid, you can buy a new plan or top-up with more data. If your current eSIM has expired, you will need to buy a new one.', isOpen: false }
    
  ];

  togglePanel(index: number) {
    this.panels[index].isOpen = !this.panels[index].isOpen;
  }

}
